server:
  port: 8083
  servlet:
    context-path: /LangChainJavaChat

spring:
  application:
    name: LangChainJavaChat
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

langchain4j:
  open-ai:
    chat-model:
      # You can use "demo" api key for demonstration purposes.
      # You can get your own OpenAI API key here: https://platform.openai.com/account/api-keys
      api-key: "demo"
      log-requests: true
      log-responses: true

logging:
  level:
    dev:
      langchain4j: debug
      ai4j:
        openai4j: debug