server:
  port: 8083
  servlet:
    context-path: /LangChainJavaChat

spring:
  application:
    name: LangChainJavaChat
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

langchain4j:
  open-ai:
    chat-model:
      log-requests: true
      log-responses: true
      api-key: "demo"

logging:
  level:
    dev:
      langchain4j: debug
      ai4j:
        openai4j: debug